navigation:
  - label: "Dashboard"
    name: dashboard
    href: "app_dashboard"
    role: "ROLE_USER"
    sub:
  - label: "Marketing"
    name: marketing
    href: "app_marketing"
    role: "ROLE_USER"
    sub:
      - label: "Articles"
        href: "app_articles"
        role: "ROLE_USER"
      - label: "Réalisations"
        href: "app_realization"
        role: "ROLE_USER"
  - label: "Configuration"
    name: configuration
    href: "app_configuration"
    role: "ROLE_USER"
    sub:
  - label: "Déconnexion"
    name: logout
    href: "app_logout"
    role: "ROLE_USER"
    sub: